name: ukintensity_integration
description: Returns information from the UK National Grid's carbon intensity API
version: 1.0.1
repository: https://github.com/jordansrowles/ukintensity_integration

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  http: ^0.13.5
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
